### ISSUE TITLE
Make new user super admin

### ISSUE THREAD

**Issue by cratedev** [mbecker20/komodo#173]
I installed Komodo with mongodb a while back, and was using local auth (account name: admin). 

I then switched to using OIDC, but my OIDC user (server) is of course different. I'd like to make "server" the super admin, and remove "admin".

Is there a simple way to do that?

**Comment by cratedev** [comment]
I managed to figure it out after a lot of trial and error. Basically:
Run mongosh, connect to the komodo db, and then update the User collection:

`db.User.updateOne({username: 'server'}, {$set:{admin:true}})
db.User.updateOne({username: 'server'}, {$set:{super_admin:true}})`

**Comment by mpkossen** [comment]
For someone coming across this, you can connect to your MongoDB using the following command (replace 'komodo-mongo-1' with the name of your docker container):

`docker exec -it komodo-mongo-1 mongosh "mongodb://localhost:27017" --username komodo`

You will be asked for your password.

Once logged in, select the right database:

`use komodo`

And then run the commands referenced above with the right username.

Personally, I think there should be a toggle for this in the interface.

**Comment by Hutch79** [comment]
Since the implementation of the Komodo cli, it is possible to promote an existing admin user to super-admin, and also demote a super-admin to admin.  
This means, your new user already needs to be Admin! I have found no way to promote a user to admin.

The command to use is as follows:
`km set user <username> super-admin true`
