### ISSUE TITLE
[Feature] Obscure variable length if secret is toggled

### ISSUE THREAD

**Issue by seraphblade2010** [mbecker20/komodo#206]
Currently one can see the exact length that a variable has even if the secret toggle is toggled.
I think komodo should at least obscure the actual length of the variable if it is treated as a secret.

**Comment by mbecker20** [comment]
The UI managed Variables are retrievable via API for all Admin level users due to their need to manage these: https://komo.do/docs/variables#defining-variables-and-secrets. If you login as a **non-admin user**, you will see for variables marked as secret, **the values are completely unavailable for view, including their length**. Since you are logged in as admin user, your UI will load the UI managed variables from the api, including plain values. Other than this permission based block, there is no additional security protections around the UI managed Variables, with an admin level API key you can query them in plain text.
